name = "admin"
version = "0.1.0"
description = "Standalone admin example resource"
authors = ["MeowV Team"]
license = "MIT"
tags = ["admin", "example"]
protocol_version = 2
edition_compatibility = "any"
platform_compatibility = "any"

[entrypoints]
server = "server/main.js"
client = "client/main.js"

[[dependencies]]
name = "chat"

[[dependencies]]
name = "scoreboard"
